"use client";

import { useActionState, useState } from "react";

import { createComplaintAction, transitionComplaintAction, updateComplaintAction } from "@/app/complaints/actions";
import type { ComplaintWorkspace } from "@/lib/pilot-data";

type ActionState = { error: string | null; success: string | null };
const initial: ActionState = { error: null, success: null };
const field = "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const area = "min-h-24 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";

function Message({ state }: { state: ActionState }) { return state.error || state.success ? <p role="status" className={`text-xs font-semibold ${state.error ? "text-rose-700" : "text-emerald-700"}`}>{state.error ?? state.success}</p> : null; }

export function ComplaintCreateForm({ data }: { data: ComplaintWorkspace }) {
  const [state, action, pending] = useActionState(createComplaintAction, initial); const [customerId, setCustomerId] = useState(""); const [branchId, setBranchId] = useState("");
  return <form action={action} className="space-y-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Keluhan baru</p><h2 className="mt-1 text-lg font-bold">Catat masalah pelanggan</h2></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Cabang<select name="branchId" required value={branchId} onChange={(event) => setBranchId(event.target.value)} className={`${field} mt-1`}><option value="">Pilih cabang</option>{data.branches.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Pelanggan<select name="customerId" required value={customerId} onChange={(event) => setCustomerId(event.target.value)} className={`${field} mt-1`}><option value="">Pilih pelanggan</option>{data.customers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div>
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-600">Booking<select name="bookingId" className={`${field} mt-1`}><option value="">Tanpa booking</option>{data.bookings.filter((row) => (!customerId || row.customerId === customerId) && (!branchId || row.branchId === branchId)).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Hewan<select name="petId" className={`${field} mt-1`}><option value="">Tanpa hewan</option>{data.pets.filter((row) => !customerId || row.customerId === customerId).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Groomer terkait<select name="resourceId" className={`${field} mt-1`}><option value="">Belum ditentukan</option>{data.resources.filter((row) => !branchId || row.branchId === branchId).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Kategori<select name="category" defaultValue="service_quality" className={`${field} mt-1`}><option value="service_quality">Kualitas layanan</option><option value="injury">Cedera</option><option value="behavior">Penanganan perilaku</option><option value="billing">Tagihan</option><option value="lateness">Keterlambatan</option><option value="communication">Komunikasi</option><option value="other">Lainnya</option></select></label><label className="text-xs font-semibold text-slate-600">Keparahan<select name="severity" defaultValue="medium" className={`${field} mt-1`}><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select></label></div>
    <label className="block text-xs font-semibold text-slate-600">Judul<input name="title" required minLength={3} maxLength={160} className={`${field} mt-1`} placeholder="Ringkasan masalah" /></label><label className="block text-xs font-semibold text-slate-600">Kronologi<textarea name="description" required minLength={3} maxLength={4000} className={`${area} mt-1`} placeholder="Apa yang terjadi, kapan, dan dampaknya?" /></label>
    <div className="flex items-center justify-between gap-3"><Message state={state} /><button disabled={pending} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{pending ? "Menyimpan…" : "Buat keluhan"}</button></div>
  </form>;
}

export function ComplaintActions({ complaint, resources }: { complaint: ComplaintWorkspace["rows"][number]; resources: ComplaintWorkspace["resources"] }) {
  const [updateState, updateAction, updating] = useActionState(updateComplaintAction, initial); const [transitionState, transitionAction, transitioning] = useActionState(transitionComplaintAction, initial);
  const branchResources = resources.filter((row) => row.branchId === complaint.branchId);
  return <div className="mt-4 grid gap-4 border-t border-slate-100 pt-4 lg:grid-cols-2">
    <form action={updateAction} className="space-y-2 rounded-2xl bg-slate-50 p-3"><input type="hidden" name="complaintId" value={complaint.id} /><p className="text-xs font-bold">Penanggung jawab & pemulihan</p><div className="grid gap-2 sm:grid-cols-2"><select name="severity" defaultValue={complaint.severity} className={field}><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select><select name="resourceId" defaultValue={complaint.resourceId ?? ""} className={field}><option value="">Tanpa groomer</option>{branchResources.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><textarea name="resolutionNotes" defaultValue={complaint.resolutionNotes ?? ""} className={area} placeholder="Temuan atau catatan penyelesaian" /><textarea name="recoveryAction" defaultValue={complaint.recoveryAction ?? ""} className={area} placeholder="Refund, grooming ulang, komunikasi, atau tindakan pemulihan" /><div className="flex items-center justify-between gap-2"><Message state={updateState} /><button disabled={updating} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">{updating ? "Menyimpan…" : "Simpan detail"}</button></div></form>
    <form action={transitionAction} className="space-y-2 rounded-2xl bg-slate-50 p-3"><input type="hidden" name="complaintId" value={complaint.id} /><p className="text-xs font-bold">Ubah status</p><textarea name="resolutionNotes" defaultValue={complaint.resolutionNotes ?? ""} className={area} placeholder="Catatan penyelesaian wajib untuk resolve/close" /><textarea name="recoveryAction" defaultValue={complaint.recoveryAction ?? ""} className={area} placeholder="Tindakan pemulihan" /><div className="flex flex-wrap gap-2">{complaint.status !== "investigating" ? <button name="to" value="investigating" disabled={transitioning} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">{complaint.status === "open" ? "Mulai investigasi" : "Buka kembali"}</button> : null}{!['resolved','closed'].includes(complaint.status) ? <button name="to" value="resolved" disabled={transitioning} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Selesaikan</button> : null}{complaint.status !== "closed" ? <button name="to" value="closed" disabled={transitioning} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Tutup</button> : null}</div><Message state={transitionState} /></form>
  </div>;
}
