"use client";

import { useActionState, useState } from "react";
import { createOnboardingLinkAction, reviewOnboardingAction, revokeOnboardingLinkAction, type OnboardingActionState } from "@/app/customers/onboarding/actions";

type LinkRow = { id:string; status:string; source:string|null; internal_note:string|null; expires_at:string; created_at:string };
type SubmissionRow = { id:string; payload:Record<string,unknown>; created_at:string };
const initial: OnboardingActionState = { error:null, success:null };

export function OnboardingAdmin({ links, submissions, customers }: { links:LinkRow[]; submissions:SubmissionRow[]; customers:Array<{id:string;name:string;phone:string|null}> }) {
  const [state, action, pending] = useActionState(createOnboardingLinkAction, initial);
  const [copied, setCopied] = useState(false);
  const link = state.linkPath && typeof window !== "undefined" ? `${window.location.origin}${state.linkPath}` : "";
  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-bold">Buat link pendaftaran</h2><p className="mt-1 text-xs text-slate-500">Satu kali pakai, kedaluwarsa otomatis dalam dua hari.</p><form action={action} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input name="source" className="field" placeholder="Sumber, contoh Instagram" /><input name="note" className="field" placeholder="Catatan lead internal" /><button disabled={pending} className="rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">{pending?"Membuat…":"Buat link"}</button></form>{state.error||state.success?<p className={`mt-3 text-xs font-semibold ${state.error?"text-rose-700":"text-emerald-700"}`}>{state.error??state.success}</p>:null}{link?<div className="mt-3 flex gap-2"><input readOnly value={link} className="field"/><button type="button" onClick={async()=>{await navigator.clipboard.writeText(link);setCopied(true)}} className="rounded-xl border px-4 text-xs font-bold">{copied?"Tersalin":"Salin"}</button><a href={`https://wa.me/?text=${encodeURIComponent(`Halo kak! Isi data kamu dan anabul melalui link Operro ini ya:\n\n${link}\n\nLink berlaku dua hari.`)}`} target="_blank" rel="noreferrer" className="grid place-items-center rounded-xl bg-emerald-50 px-4 text-xs font-bold text-emerald-800">WhatsApp</a></div>:null}</section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-bold">Menunggu review ({submissions.length})</h2><div className="mt-4 space-y-3">{submissions.length===0?<p className="text-sm text-slate-400">Belum ada pendaftaran baru.</p>:submissions.map((row)=>{const p=row.payload;const pets=Array.isArray(p.pets)?p.pets as Array<Record<string,unknown>>:[];const referenceCount=pets.reduce((sum,pet)=>sum+(Array.isArray(pet.styleReferences)?pet.styleReferences.length:0),0);const phone=String(p.phone??"");const duplicates=customers.filter((customer)=>customer.phone?.replace(/\D/g,"")===phone.replace(/\D/g,""));return <article key={row.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{String(p.customerName??"Pelanggan")}</p><p className="text-xs text-slate-500">{phone} · {String(p.kecamatan??"")}, {String(p.kabupatenKota??"")} · {pets.length} hewan{referenceCount?` · ${referenceCount} referensi gaya`:""}</p></div><span className="text-xs text-slate-400">{new Date(row.created_at).toLocaleString("id-ID")}</span></div><div className="mt-3 flex flex-wrap gap-2">{pets.map((pet,index)=><span key={index} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{String(pet.name??"?")} · {String(pet.breed??pet.species??"")}{Array.isArray(pet.styleReferences)&&pet.styleReferences.length?` · ${pet.styleReferences.length} foto`:""}</span>)}</div>{duplicates.length?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800">Nomor ini cocok dengan: {duplicates.map(d=>d.name).join(", ")}. Pilih pelanggan tersebut untuk menambahkan hewan tanpa membuat duplikat.</p>:null}<form action={reviewOnboardingAction} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="submissionId" value={row.id}/><select name="mergeCustomerId" className="h-10 rounded-xl border px-3 text-xs"><option value="">Buat pelanggan baru</option>{duplicates.map(d=><option key={d.id} value={d.id}>Gabung ke {d.name}</option>)}</select><button name="decision" value="approve" className="rounded-xl bg-emerald-700 px-4 text-xs font-bold text-white">Setujui</button><button name="decision" value="reject" className="rounded-xl border border-rose-200 px-4 text-xs font-bold text-rose-700">Tolak</button></form></article>})}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-bold">Riwayat link</h2><div className="mt-4 space-y-2">{links.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="text-xs font-bold uppercase">{row.status}{row.status==="active"&&new Date(row.expires_at)<new Date()?" · kedaluwarsa":""}</p><p className="text-xs text-slate-500">{row.source??"Tanpa sumber"}{row.internal_note?` · ${row.internal_note}`:""}</p></div>{row.status==="active"?<form action={revokeOnboardingLinkAction}><input type="hidden" name="id" value={row.id}/><button className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Cabut</button></form>:null}</div>)}</div></section>
  </div>;
}
