import Link from "next/link";

import { ComplaintActions, ComplaintCreateForm } from "@/components/complaint-workspace";
import { EmptyState, PageHeader, StatCard } from "@/components/pilot-ui";
import { RestrictedNotice } from "@/components/restricted-notice";
import { WorkspaceShell } from "@/components/workspace-shell";
import { loadComplaintWorkspace } from "@/lib/pilot-data";
import { requireActiveWorkspace } from "@/lib/require-workspace";

export const metadata = { title: "Keluhan" };
const STATUS: Record<string, string> = { open: "Terbuka", investigating: "Investigasi", resolved: "Selesai", closed: "Ditutup" };
const CATEGORY: Record<string, string> = { service_quality: "Kualitas layanan", injury: "Cedera", behavior: "Perilaku", billing: "Tagihan", lateness: "Keterlambatan", communication: "Komunikasi", other: "Lainnya" };

export default async function ComplaintsPage({ searchParams }: { searchParams: Promise<{ status?: string; severity?: string }> }) {
  const workspace = await requireActiveWorkspace(); const filters = await searchParams;
  const header = <PageHeader eyebrow="Service recovery" title="Keluhan pelanggan" description="Kelola kronologi, investigasi, tingkat risiko, pemulihan, dan audit sampai keluhan ditutup." action={<a href={`/api/complaints/export?status=${encodeURIComponent(filters.status ?? "")}&severity=${encodeURIComponent(filters.severity ?? "")}`} className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800">Export CSV</a>} />;
  const canRead = workspace.capabilities["customer.read"] || workspace.capabilities["task.manage"] || workspace.capabilities["reports.view"]; if (!canRead) return <WorkspaceShell {...workspace} activePath="/complaints">{header}<div className="mt-7"><RestrictedNotice title="Tidak ada izin keluhan" description="Peran ini memerlukan customer.read, task.manage, atau reports.view." /></div></WorkspaceShell>;
  const data = await loadComplaintWorkspace(workspace.supabase, workspace.activeOrganization.id, filters); const canManage = workspace.capabilities["task.manage"] || workspace.capabilities["customer.manage"];
  const active = data.rows.filter((row) => ["open", "investigating"].includes(row.status)).length; const critical = data.rows.filter((row) => row.severity === "critical" && row.status !== "closed").length; const resolved = data.rows.filter((row) => ["resolved", "closed"].includes(row.status)).length;
  return <WorkspaceShell {...workspace} activePath="/complaints">{header}
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><StatCard label="Aktif" value={String(active)} helper="Terbuka atau investigasi." tone={active ? "warning" : "success"} /><StatCard label="Kritis aktif" value={String(critical)} helper="Prioritas service recovery." tone={critical ? "warning" : "success"} /><StatCard label="Selesai" value={String(resolved)} helper="Resolved atau closed." tone="success" /></div>
    <form className="mt-6 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-4"><select name="status" defaultValue={filters.status ?? ""} className="h-10 rounded-xl border border-slate-200 px-3 text-xs"><option value="">Semua status</option><option value="open">Terbuka</option><option value="investigating">Investigasi</option><option value="resolved">Selesai</option><option value="closed">Ditutup</option></select><select name="severity" defaultValue={filters.severity ?? ""} className="h-10 rounded-xl border border-slate-200 px-3 text-xs"><option value="">Semua keparahan</option><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select><button className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Terapkan</button><Link href="/complaints" className="rounded-xl border px-4 py-2 text-xs font-bold">Reset</Link></form>
    {canManage ? <div className="mt-6"><ComplaintCreateForm data={data} /></div> : null}
    <section className="mt-7 space-y-4">{data.rows.length === 0 ? <div className="rounded-3xl border bg-white p-6"><EmptyState title="Belum ada keluhan" description="Keluhan yang sesuai filter akan muncul di sini." /></div> : data.rows.map((row) => <article key={row.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-slate-400">{row.referenceCode}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${row.severity === "critical" ? "bg-rose-100 text-rose-800" : row.severity === "high" ? "bg-orange-100 text-orange-800" : "bg-amber-50 text-amber-800"}`}>{row.severity}</span><span className="rounded-full bg-sky-50 px-2 py-1 text-[10px] font-bold uppercase text-sky-800">{STATUS[row.status] ?? row.status}</span></div><h2 className="mt-2 text-lg font-bold">{row.title}</h2><p className="mt-1 text-xs text-slate-500"><Link href={`/customers/${row.customerId}`} className="font-bold text-sky-800 hover:underline">{row.customerName}</Link> · {row.branchName}{row.petName ? ` · ${row.petName}` : ""}{row.resourceName ? ` · ${row.resourceName}` : ""}</p></div><div className="text-right text-xs text-slate-500"><p>{CATEGORY[row.category] ?? row.category}</p><p className="mt-1">{new Date(row.reportedAt).toLocaleString("id-ID", { dateStyle: "medium", timeStyle: "short" })}</p>{row.bookingId ? <Link href={`/operations?booking=${row.bookingId}`} className="mt-1 inline-block font-bold text-sky-800">Buka booking</Link> : null}</div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700">{row.description}</p>{row.resolutionNotes || row.recoveryAction ? <div className="mt-4 grid gap-3 rounded-2xl bg-emerald-50/70 p-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-700">Penyelesaian</p><p className="mt-1 text-xs text-emerald-950">{row.resolutionNotes ?? "Belum diisi"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-700">Pemulihan</p><p className="mt-1 text-xs text-emerald-950">{row.recoveryAction ?? "Belum diisi"}</p></div></div> : null}<details className="mt-4 rounded-xl border border-slate-100 p-3"><summary className="cursor-pointer text-xs font-bold">Audit aktivitas ({row.history.length})</summary><div className="mt-3 space-y-2">{row.history.map((event, index) => <div key={`${event.occurredAt}-${index}`} className="border-l-2 border-slate-200 pl-3"><p className="text-xs font-semibold">{event.summary ?? event.type}</p><p className="text-[11px] text-slate-400">{new Date(event.occurredAt).toLocaleString("id-ID")}</p></div>)}</div></details>{canManage ? <ComplaintActions complaint={row} resources={data.resources} /> : null}</article>)}</section>
  </WorkspaceShell>;
}
